### PR TITLE
New try to fix the pr for the Fixed build issuee can only be default-imported using the 'esModule

### PR DESCRIPTION
**Pull request by JimmyBjorklund**
https://github.com/coapjs/node-coap/pull/378

### CODE REVIEW

**Comment by JKRhb** [comment]
Thank you, @JimmyBjorklund, now the workflows are working again :) Very weird that the checks weren't running in the other PR 🤔

**Review by JKRhb — APPROVED** [review]

**Review by Apollon77 — APPROVED** [review]

**Comment by JKRhb** [comment]
Hmm, now it seems like there is a Node 20 related issue :/

**Comment by Apollon77** [comment]
@JKRhb https://github.com/coapjs/node-coap/issues/380 ?

**Comment by JKRhb** [comment]
> @JKRhb #380 ?

Oh, right 😅 Then I guess we can merge this one and continue working on #380 afterward? :)

**Comment by Apollon77** [comment]
ok for me

**Pull request merged**
