### PR TITLE
Create FUNDING.md

### PR DESCRIPTION
**Pull request by Apollon77**
@mcollina Are you ok with adding also add to the sponsoring for the library?

### CODE REVIEW

**Review by JKRhb — APPROVED** [review]

**Comment by mcollina** [comment]
Please don't include me. I don't plan to maintain this library anymore.

@Apollon77 may I move this to you?

**Comment by Apollon77** [comment]
@mcollina All good, we take over :-)

Please move to https://github.com/coapjs orga ... I synced with @JKRhb and we think thats best. it is just founded orga and maybe easier for the future to manage stuff.

What do you think about the idea that we also take over coap-packet ? I think for that I would then also need npm rights ifyou think it is a good idea.

**Comment by mcollina** [comment]
can you invite me to the org? I'll move both packages.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Apollon77** [comment]
@mcollina Thank you for your trust the last year! I'm sure we see us again in several projects ;-)

**Pull request merged**
